export const QUESTIONS = [
    // --- MATH SECTION (1-25) ---
    { id: 1, sub: 'Math', q_en: "Value of sin 30°?", q_hi: "sin 30° का मान क्या है?", opts_en: ["1", "1/2", "0", "√3/2"], opts_hi: ["1", "1/2", "0", "√3/2"], ans: "1/2" },
    { id: 2, sub: 'Math', q_en: "Area of Circle?", q_hi: "वृत्त का क्षेत्रफल?", opts_en: ["πr²", "2πr", "πd", "r²"], opts_hi: ["πr²", "2πr", "πd", "r²"], ans: "πr²" },
    { id: 3, sub: 'Math', q_en: "HCF of 135 and 225?", q_hi: "135 और 225 का HCF क्या है?", opts_en: ["15", "45", "75", "135"], opts_hi: ["15", "45", "75", "135"], ans: "45" },
    { id: 4, sub: 'Math', q_en: "Degree of a Linear Equation?", q_hi: "रैखिक समीकरण की घात क्या होती है?", opts_en: ["1", "2", "3", "0"], opts_hi: ["1", "2", "3", "0"], ans: "1" },
    { id: 5, sub: 'Math', q_en: "Pythagoras theorem applies to?", q_hi: "पायथागॉरियन प्रमेय किस पर लागू होता है?", opts_en: ["Circle", "Right Triangle", "Square", "Rectangle"], opts_hi: ["वृत्त", "समकोण त्रिभुज", "वर्ग", "आयत"], ans: "Right Triangle" },
    { id: 6, sub: 'Math', q_en: "Value of cos 0°?", q_hi: "cos 0° का मान क्या है?", opts_en: ["0", "1", "1/2", "Not defined"], opts_hi: ["0", "1", "1/2", "परिभाषित नहीं"], ans: "1" },
    { id: 7, sub: 'Math', q_en: "Probability of an impossible event?", q_hi: "असंभव घटना की प्रायिकता क्या है?", opts_en: ["1", "0", "0.5", "-1"], opts_hi: ["1", "0", "0.5", "-1"], ans: "0" },
    { id: 8, sub: 'Math', q_en: "Volume of a Cube with side 'a'?", q_hi: "भुजा 'a' वाले घन का आयतन?", opts_en: ["a²", "a³", "4a", "6a²"], opts_hi: ["a²", "a³", "4a", "6a²"], ans: "a³" },
    { id: 9, sub: 'Math', q_en: "Discriminant (D) formula?", q_hi: "विविक्तकर (D) का सूत्र?", opts_en: ["b²-4ac", "b-4ac", "b²+4ac", "2b-ac"], opts_hi: ["b²-4ac", "b-4ac", "b²+4ac", "2b-ac"], ans: "b²-4ac" },
    { id: 10, sub: 'Math', q_en: "Value of tan 45°?", q_hi: "tan 45° का मान क्या है?", opts_en: ["0", "1", "√3", "1/√3"], opts_hi: ["0", "1", "√3", "1/√3"], ans: "1" },
    { id: 11, sub: 'Math', q_en: "Sum of first 10 natural numbers?", q_hi: "प्रथम 10 प्राकृतिक संख्याओं का योग?", opts_en: ["45", "50", "55", "60"], opts_hi: ["45", "50", "55", "60"], ans: "55" },
    { id: 12, sub: 'Math', q_en: "Formula for Circumference of Circle?", q_hi: "वृत्त की परिधि का सूत्र?", opts_en: ["πr²", "2πr", "πd²", "2πd"], opts_hi: ["πr²", "2πr", "πd²", "2πd"], ans: "2πr" },
    { id: 13, sub: 'Math', q_en: "Mode is the?", q_hi: "बहुलक क्या होता है?", opts_en: ["Middle value", "Average", "Most frequent value", "Total sum"], opts_hi: ["मध्य मान", "औसत", "सर्वाधिक बार आने वाला मान", "कुल योग"], ans: "Most frequent value" },
    { id: 14, sub: 'Math', q_en: "Distance between (0,0) and (3,4)?", q_hi: "बिंदु (0,0) और (3,4) के बीच की दूरी?", opts_en: ["5", "7", "1", "25"], opts_hi: ["5", "7", "1", "25"], ans: "5" },
    { id: 15, sub: 'Math', q_en: "The zero of 2x + 3 is?", q_hi: "2x + 3 का शून्यक क्या है?", opts_en: ["3/2", "-3/2", "2/3", "-2/3"], opts_hi: ["3/2", "-3/2", "2/3", "-2/3"], ans: "-3/2" },
    { id: 16, sub: 'Math', q_en: "Volume of Cylinder?", q_hi: "बेलन का आयतन?", opts_en: ["πr²h", "2πrh", "1/3 πr²h", "πrl"], opts_hi: ["πr²h", "2πrh", "1/3 πr²h", "πrl"], ans: "πr²h" },
    { id: 17, sub: 'Math', q_en: "Surface area of Sphere?", q_hi: "गोले का पृष्ठीय क्षेत्रफल?", opts_en: ["2πr²", "3πr²", "4πr²", "πr²"], opts_hi: ["2πr²", "3πr²", "4πr²", "πr²"], ans: "4πr²" },
    { id: 18, sub: 'Math', q_en: "cosec 90° value?", q_hi: "cosec 90° का मान?", opts_en: ["0", "1", "Not defined", "1/2"], opts_hi: ["0", "1", "परिभाषित नहीं", "1/2"], ans: "1" },
    { id: 19, sub: 'Math', q_en: "Median of 1, 3, 5, 7, 9 is?", q_hi: "1, 3, 5, 7, 9 की माध्यिका क्या है?", opts_en: ["3", "5", "7", "1"], opts_hi: ["3", "5", "7", "1"], ans: "5" },
    { id: 20, sub: 'Math', q_en: "Sum of angles in a triangle?", q_hi: "त्रिभुज के कोणों का योग?", opts_en: ["90°", "180°", "360°", "270°"], opts_hi: ["90°", "180°", "360°", "270°"], ans: "180°" },
    { id: 21, sub: 'Math', q_en: "What is the square root of 625?", q_hi: "625 का वर्गमूल क्या है?", opts_en: ["15", "25", "35", "45"], opts_hi: ["15", "25", "35", "45"], ans: "25" },
    { id: 22, sub: 'Math', q_en: "Is 2 a prime number?", q_hi: "क्या 2 एक अभाज्य संख्या है?", opts_en: ["Yes", "No", "Maybe", "Don't know"], opts_hi: ["हाँ", "नहीं", "शायद", "पता नहीं"], ans: "Yes" },
    { id: 23, sub: 'Math', q_en: "Roots of x² - 4 = 0?", q_hi: "x² - 4 = 0 के मूल क्या हैं?", opts_en: ["2, -2", "2, 0", "4, -4", "1, -1"], opts_hi: ["2, -2", "2, 0", "4, -4", "1, -1"], ans: "2, -2" },
    { id: 24, sub: 'Math', q_en: "Mid-point of (2,4) and (4,6)?", q_hi: "(2,4) और (4,6) का मध्य-बिंदु?", opts_en: ["(3,5)", "(2,5)", "(3,4)", "(6,10)"], opts_hi: ["(3,5)", "(2,5)", "(3,4)", "(6,10)"], ans: "(3,5)" },
    { id: 25, sub: 'Math', q_en: "Lateral surface area of Cube?", q_hi: "घन का वक्र पृष्ठीय क्षेत्रफल?", opts_en: ["4a²", "6a²", "a²", "a³"], opts_hi: ["4a²", "6a²", "a²", "a³"], ans: "4a²" },

    // --- SCIENCE SECTION (26-50) ---
    { id: 26, sub: 'Science', q_en: "Chemical formula of Water?", q_hi: "पानी का रासायनिक सूत्र?", opts_en: ["H2O", "D2O", "H2O2", "HO2"], opts_hi: ["H2O", "D2O", "H2O2", "HO2"], ans: "H2O" },
    { id: 27, sub: 'Science', q_en: "Powerhouse of cell?", q_hi: "कोशिका का शक्तिगृह?", opts_en: ["Nucleus", "Mitochondria", "Ribosome", "Cell Wall"], opts_hi: ["केंद्रक", "माइटोकॉन्ड्रिया", "राइबोसोम", "कोशिका भित्ति"], ans: "Mitochondria" },
    { id: 28, sub: 'Science', q_en: "pH value of Acidic solution?", q_hi: "अम्लीय विलयन का pH मान?", opts_en: ["< 7", "> 7", "= 7", "14"], opts_hi: ["< 7", "> 7", "= 7", "14"], ans: "< 7" },
    { id: 29, sub: 'Science', q_en: "Gas evolved during Photosynthesis?", q_hi: "प्रकाश संश्लेषण के दौरान कौन सी गैस निकलती है?", opts_en: ["CO2", "O2", "N2", "H2"], opts_hi: ["CO2", "O2", "N2", "H2"], ans: "O2" },
    { id: 30, sub: 'Science', q_en: "Unit of Electric Current?", q_hi: "विद्युत धारा का मात्रक?", opts_en: ["Volt", "Ampere", "Ohm", "Watt"], opts_hi: ["वोल्ट", "एम्पीयर", "ओम", "वाट"], ans: "Ampere" },
    { id: 31, sub: 'Science', q_en: "Which mirror is used in car side mirrors?", q_hi: "गाड़ी के साइड मिरर में कौन सा दर्पण उपयोग होता है?", opts_en: ["Concave", "Convex", "Plain", "Bifocal"], opts_hi: ["अवतल", "उत्तल", "समतल", "द्वि-फोकसी"], ans: "Convex" },
    { id: 32, sub: 'Science', q_en: "Main component of Natural Gas?", q_hi: "प्राकृतिक गैस का मुख्य घटक?", opts_en: ["Methane", "Ethane", "Propane", "Butane"], opts_hi: ["मीथेन", "ईथेन", "प्रोपेन", "ब्यूटेन"], ans: "Methane" },
    { id: 33, sub: 'Science', q_en: "Acid present in Lemon?", q_hi: "नींबू में कौन सा अम्ल होता है?", opts_en: ["Lactic", "Citric", "Acetic", "Oxalic"], opts_hi: ["लैक्टिक", "साइट्रिक", "एसिटिक", "ऑक्सेलिक"], ans: "Citric" },
    { id: 34, sub: 'Science', q_en: "Smallest unit of life?", q_hi: "जीवन की सबसे छोटी इकाई?", opts_en: ["Tissue", "Organ", "Cell", "Atom"], opts_hi: ["ऊतक", "अंग", "कोशिका", "परमाणु"], ans: "Cell" },
    { id: 35, sub: 'Science', q_en: "Gas used in chips packets?", q_hi: "चिप्स के पैकेट में कौन सी गैस होती है?", opts_en: ["Oxygen", "Nitrogen", "Argon", "Helium"], opts_hi: ["ऑक्सीजन", "नाइट्रोजन", "आर्गन", "हीलियम"], ans: "Nitrogen" },
    { id: 36, sub: 'Science', q_en: "Normal Human Blood Pressure?", q_hi: "सामान्य मानव रक्तचाप?", opts_en: ["120/80", "100/60", "140/90", "110/70"], opts_hi: ["120/80", "100/60", "140/90", "110/70"], ans: "120/80" },
    { id: 37, sub: 'Science', q_en: "Speed of light in vacuum?", q_hi: "निर्वात में प्रकाश की चाल?", opts_en: ["3x10^8 m/s", "2x10^8 m/s", "3x10^5 m/s", "1x10^8 m/s"], opts_hi: ["3x10^8 m/s", "2x10^8 m/s", "3x10^5 m/s", "1x10^8 m/s"], ans: "3x10^8 m/s" },
    { id: 38, sub: 'Science', q_en: "Formula of Baking Soda?", q_hi: "बेकिंग सोडा का सूत्र?", opts_en: ["NaHCO3", "Na2CO3", "NaOH", "NaCl"], opts_hi: ["NaHCO3", "Na2CO3", "NaOH", "NaCl"], ans: "NaHCO3" },
    { id: 39, sub: 'Science', q_en: "Which metal is liquid at room temperature?", q_hi: "कमरे के तापमान पर कौन सी धातु द्रव है?", opts_en: ["Iron", "Mercury", "Gold", "Silver"], opts_hi: ["लोहा", "पारा", "सोना", "चांदी"], ans: "Mercury" },
    { id: 40, sub: 'Science', q_en: "Vitamin C deficiency causes?", q_hi: "विटामिन C की कमी से क्या होता है?", opts_en: ["Rickets", "Scurvy", "Beriberi", "Night blindness"], opts_hi: ["रिकेट्स", "स्कर्वी", "बेरीबेरी", "रतौंधी"], ans: "Scurvy" },
    { id: 41, sub: 'Science', q_en: "Hormone that controls blood sugar?", q_hi: "रक्त शर्करा को नियंत्रित करने वाला हार्मोन?", opts_en: ["Adrenaline", "Insulin", "Thyroxine", "Estrogen"], opts_hi: ["एड्रेनालिन", "इंसुलिन", "थायरोक्सिन", "एस्ट्रोजन"], ans: "Insulin" },
    { id: 42, sub: 'Science', q_en: "Unit of Force?", q_hi: "बल का मात्रक?", opts_en: ["Joule", "Watt", "Newton", "Pascal"], opts_hi: ["जूल", "वाट", "न्यूटन", "पास्कल"], ans: "Newton" },
    { id: 43, sub: 'Science', q_en: "Non-metal that conducts electricity?", q_hi: "अधातु जो बिजली का संवाहक है?", opts_en: ["Diamond", "Graphite", "Sulphur", "Iodine"], opts_hi: ["हीरा", "ग्रेफाइट", "सल्फर", "आयोडीन"], ans: "Graphite" },
    { id: 44, sub: 'Science', q_en: "The focus length of a plane mirror is?", q_hi: "समतल दर्पण की फोकस दूरी क्या होती है?", opts_en: ["Zero", "Finite", "Infinite", "25 cm"], opts_hi: ["शून्य", "निश्चित", "अनंत", "25 cm"], ans: "Infinite" },
    { id: 45, sub: 'Science', q_en: "Color of Phenolphthalein in Base?", q_hi: "क्षार में फेनोल्फथेलिन का रंग?", opts_en: ["Colorless", "Pink", "Blue", "Red"], opts_hi: ["रंगहीन", "गुलाबी", "नीला", "लाल"], ans: "Pink" },
    { id: 46, sub: 'Science', q_en: "Which part of leaf performs photosynthesis?", q_hi: "पत्ती का कौन सा भाग प्रकाश संश्लेषण करता है?", opts_en: ["Stomata", "Chloroplast", "Veins", "Petiole"], opts_hi: ["रंध्र", "क्लोरोप्लास्ट", "शिराएं", "पर्णवृंत"], ans: "Chloroplast" },
    { id: 47, sub: 'Science', q_en: "Rusting of iron is a?", q_hi: "लोहे में जंग लगना एक है?", opts_en: ["Physical change", "Chemical change", "No change", "Biological change"], opts_hi: ["भौतिक परिवर्तन", "रासायनिक परिवर्तन", "कोई परिवर्तन नहीं", "जैविक परिवर्तन"], ans: "Chemical change" },
    { id: 48, sub: 'Science', q_en: "Human heart has how many chambers?", q_hi: "मानव हृदय में कितने कोष्ठक होते हैं?", opts_en: ["2", "3", "4", "1"], opts_hi: ["2", "3", "4", "1"], ans: "4" },
    { id: 49, sub: 'Science', q_en: "Ozone layer protects us from?", q_hi: "ओजोन परत हमारी रक्षा किससे करती है?", opts_en: ["X-rays", "UV rays", "Infrared", "Gamma rays"], opts_hi: ["X-किरणों", "UV किरणों", "अवरक्त", "गामा किरणों"], ans: "UV rays" },
    { id: 50, sub: 'Science', q_en: "Acid in Curd?", q_hi: "दही में कौन सा अम्ल है?", opts_en: ["Citric", "Oxalic", "Lactic", "Tartaric"], opts_hi: ["साइट्रिक", "ऑक्सेलिक", "लैक्टिक", "टार्टरिक"], ans: "Lactic" },

    // --- ENGLISH SECTION (51-75) ---
    { id: 51, sub: 'English', q_en: "Synonym of 'Happy'?", q_hi: "'Happy' का पर्यायवाची?", opts_en: ["Sad", "Angry", "Joyful", "Upset"], opts_hi: ["Sad", "Angry", "Joyful", "Upset"], ans: "Joyful" },
    { id: 52, sub: 'English', q_en: "Antonym of 'Strong'?", q_hi: "'Strong' का विलोम?", opts_en: ["Weak", "Powerful", "Brave", "Hard"], opts_hi: ["Weak", "Powerful", "Brave", "Hard"], ans: "Weak" },
    { id: 53, sub: 'English', q_en: "Plural of 'Child'?", q_hi: "'Child' का बहुवचन?", opts_en: ["Childs", "Children", "Childrens", "Childes"], opts_hi: ["Childs", "Children", "Childrens", "Childes"], ans: "Children" },
    { id: 54, sub: 'English', q_en: "Identify the Noun: 'Delhi is beautiful.'", q_hi: "Noun चुनें: 'Delhi is beautiful.'", opts_en: ["Delhi", "is", "beautiful", "None"], opts_hi: ["Delhi", "is", "beautiful", "None"], ans: "Delhi" },
    { id: 55, sub: 'English', q_en: "Correct spelling?", q_hi: "सही वर्तनी?", opts_en: ["Receive", "Recieve", "Receve", "Recive"], opts_hi: ["Receive", "Recieve", "Receve", "Recive"], ans: "Receive" },
    { id: 56, sub: 'English', q_en: "Opposite of 'Near'?", q_hi: "'Near' का विलोम?", opts_en: ["Close", "Far", "Beside", "Next"], opts_hi: ["Close", "Far", "Beside", "Next"], ans: "Far" },
    { id: 57, sub: 'English', q_en: "Identify Verb: 'He is eating.'", q_hi: "Verb चुनें: 'He is eating.'", opts_en: ["He", "is", "eating", "None"], opts_hi: ["He", "is", "eating", "None"], ans: "eating" },
    { id: 58, sub: 'English', q_en: "Past tense of 'Go'?", q_hi: "'Go' का भूतकाल?", opts_en: ["Gone", "Went", "Going", "Goes"], opts_hi: ["Gone", "Went", "Going", "Goes"], ans: "Went" },
    { id: 59, sub: 'English', q_en: "Female of 'Lion'?", q_hi: "'Lion' का स्त्रीलिंग?", opts_en: ["Lioness", "Lions", "She-lion", "Liony"], opts_hi: ["Lioness", "Lions", "She-lion", "Liony"], ans: "Lioness" },
    { id: 60, sub: 'English', q_en: "Correct article: '___ Apple a day.'", q_hi: "Article भरें: '___ Apple a day.'", opts_en: ["A", "An", "The", "No article"], opts_hi: ["A", "An", "The", "No article"], ans: "An" },
    { id: 61, sub: 'English', q_en: "Plural of 'Mouse'?", q_hi: "'Mouse' का बहुवचन?", opts_en: ["Mouses", "Mice", "Mices", "Mouse"], opts_hi: ["Mouses", "Mice", "Mices", "Mouse"], ans: "Mice" },
    { id: 62, sub: 'English', q_en: "Synonym of 'Large'?", q_hi: "'Large' का पर्यायवाची?", opts_en: ["Small", "Big", "Thin", "Short"], opts_hi: ["Small", "Big", "Thin", "Short"], ans: "Big" },
    { id: 63, sub: 'English', q_en: "Opposite of 'Success'?", q_hi: "'Success' का विलोम?", opts_en: ["Failure", "Win", "Goal", "Pass"], opts_hi: ["Failure", "Win", "Goal", "Pass"], ans: "Failure" },
    { id: 64, sub: 'English', q_en: "Identify Adjective: 'Tall boy.'", q_hi: "Adjective चुनें: 'Tall boy.'", opts_en: ["Tall", "boy", "He", "is"], opts_hi: ["Tall", "boy", "He", "is"], ans: "Tall" },
    { id: 65, sub: 'English', q_en: "Young one of 'Cow'?", q_hi: "गाय का बच्चा?", opts_en: ["Puppy", "Kitten", "Calf", "Cub"], opts_hi: ["Puppy", "Kitten", "Calf", "Cub"], ans: "Calf" },
    { id: 66, sub: 'English', q_en: "Opposite of 'Rich'?", q_hi: "'Rich' का विलोम?", opts_en: ["Poor", "Wealthy", "Money", "Gold"], opts_hi: ["Poor", "Wealthy", "Money", "Gold"], ans: "Poor" },
    { id: 67, sub: 'English', q_en: "Plural of 'Tooth'?", q_hi: "'Tooth' का बहुवचन?", opts_en: ["Tooths", "Teeth", "Teeths", "Tooth"], opts_hi: ["Tooths", "Teeth", "Teeths", "Tooth"], ans: "Teeth" },
    { id: 68, sub: 'English', q_en: "Identify Pronoun: 'They are playing.'", q_hi: "Pronoun चुनें: 'They are playing.'", opts_en: ["Playing", "They", "Are", "None"], opts_hi: ["Playing", "They", "Are", "None"], ans: "They" },
    { id: 69, sub: 'English', q_en: "Past tense of 'See'?", q_hi: "'See' का भूतकाल?", opts_en: ["Seen", "Saw", "Seeing", "Sees"], opts_hi: ["Seen", "Saw", "Seeing", "Sees"], ans: "Saw" },
    { id: 70, sub: 'English', q_en: "Synonym of 'Fast'?", q_hi: "'Fast' का पर्यायवाची?", opts_en: ["Quick", "Slow", "Steady", "Heavy"], opts_hi: ["Quick", "Slow", "Steady", "Heavy"], ans: "Quick" },
    { id: 71, sub: 'English', q_en: "Antonym of 'Hot'?", q_hi: "'Hot' का विलोम?", opts_en: ["Warm", "Cold", "Burn", "Fire"], opts_hi: ["Warm", "Cold", "Burn", "Fire"], ans: "Cold" },
    { id: 72, sub: 'English', q_en: "Correct spelling?", q_hi: "सही वर्तनी?", opts_en: ["Beautiful", "Beatiful", "Bautiful", "Beutiful"], opts_hi: ["Beautiful", "Beatiful", "Bautiful", "Beutiful"], ans: "Beautiful" },
    { id: 73, sub: 'English', q_en: "The sun ___ in the east.", q_hi: "The sun ___ in the east.", opts_en: ["Rise", "Rises", "Rising", "Rose"], opts_hi: ["Rise", "Rises", "Rising", "Rose"], ans: "Rises" },
    { id: 74, sub: 'English', q_en: "Female of 'King'?", q_hi: "'King' का स्त्रीलिंग?", opts_en: ["Queen", "Princess", "Lady", "Woman"], opts_hi: ["Queen", "Princess", "Lady", "Woman"], ans: "Queen" },
    { id: 75, sub: 'English', q_en: "A person who teaches is a?", q_hi: "जो पढ़ाता है, उसे क्या कहते हैं?", opts_en: ["Doctor", "Teacher", "Engineer", "Farmer"], opts_hi: ["Doctor", "Teacher", "Engineer", "Farmer"], ans: "Teacher" }
];
